### ISSUE TITLE
chore: update deprecated API queries

### ISSUE THREAD

**Issue by hailelagi** [SomtochiAma/buycoins-graphql-sdk#2]
The following graphQL queries previously covered by the [buycoins public api](https://developers.buycoins.africa/) have had their functionality deprecated.

1. `cancelWithdrawal`
2. `createWithdrawal`
3. `createDepositAccount `
4. `getBankAccounts`

Please update the `README.md` documentation reflecting these changes, remove the queries and the library's interface to them, or mark them deprecated. You can learn more about the changes to [withdrawals](https://developers.buycoins.africa/naira-token-account/withdrawing-naira) and [deposit accounts](https://developers.buycoins.africa/naira-token-account/depositing-naira) in the documentation.

**Comment by somtochiama** [comment]
Hey @hailelagi, thanks for opening the issue and the pull request👌.

First, We need to decide how we handle deprecated changes. 
Removing all the code immediately might not be the best approach.
 We probably want to inform the users that the method/API(through logs and documentation)is being deprecated so that they are well informed and then remove it after some time. But if the Buycoins API has completely removed this functionality, we should probably follow suit.
 I am open to other suggestions though.

**Comment by hailelagi** [comment]
Sure, that sounds great 👍

**Comment by hailelagi** [comment]
The public api product has been shut down, If I recall since 15th of September, 2022. Making this issue stale.
